//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.TablesOLD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptScheme_Concept
    {
        public int Id { get; set; }
        public int ConceptSchemeId { get; set; }
        public string PrefLabel { get; set; }
        public string CTID { get; set; }
        public string CodedNotation { get; set; }
        public string AlternateLabel { get; set; }
        public string Description { get; set; }
        public Nullable<int> ListId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ConceptScheme ConceptScheme { get; set; }
    }
}
