//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.TablesOLD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ceNavyEntities : DbContext
    {
        public ceNavyEntities()
            : base("name=ceNavyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Codes_PropertyCategory> Codes_PropertyCategory { get; set; }
        public virtual DbSet<Codes_PropertyValue> Codes_PropertyValue { get; set; }
        public virtual DbSet<ConceptScheme_Concept> ConceptScheme_Concept { get; set; }
        public virtual DbSet<ConceptScheme> ConceptScheme { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Codes_EntityType> Codes_EntityType { get; set; }
        public virtual DbSet<Entity> Entity { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<WorkRole> WorkRole { get; set; }
        public virtual DbSet<EnlistedClassification> EnlistedClassification { get; set; }
        public virtual DbSet<Entity_Comment> Entity_Comment { get; set; }
        public virtual DbSet<OccupationalTask> OccupationalTask { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<ActivityLog> ActivityLog { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<RegistryHistory> RegistryHistory { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<Subscription_EntityType> Subscription_EntityType { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Course_Task> Course_Task { get; set; }
        public virtual DbSet<RMTLProject> RMTLProject { get; set; }
    }
}
