//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.TablesOLD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SourceDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public string CTID { get; set; }
    }
}
