-- 22-09-19 RatingContext Add ClusterAnalysisId (more likely to recreate the table) 
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ClusterAnalysis SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RatingContext ADD
	ClusterAnalysisId int NULL
GO
ALTER TABLE dbo.RatingContext ADD CONSTRAINT
	FK_RatingContext_ClusterAnalysis FOREIGN KEY
	(
	ClusterAnalysisId
	) REFERENCES dbo.ClusterAnalysis
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.RatingContext SET (LOCK_ESCALATION = TABLE)
GO
COMMIT