
--	22-10-02_create missing Unique nonclustered indices on RowId, where needed
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[Job] ADD CONSTRAINT
	[IX_Job_RowId] UNIQUE NONCLUSTERED 
	(
	RowId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.[Job] SET (LOCK_ESCALATION = TABLE)
GO
--====================================
CREATE UNIQUE NONCLUSTERED INDEX [IX_ConceptScheme.Concept_RowId] ON dbo.[ConceptScheme.Concept]
	(
	RowId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.[ConceptScheme.Concept] SET (LOCK_ESCALATION = TABLE)
GO

--====================================
ALTER TABLE dbo.[Course] ADD CONSTRAINT
	[IX_Course_RowId] UNIQUE NONCLUSTERED 
	(
	RowId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.[Course] SET (LOCK_ESCALATION = TABLE)
GO
--====================================
ALTER TABLE dbo.[WorkRole] ADD CONSTRAINT
	[IX_WorkRole_RowId] UNIQUE NONCLUSTERED 
	(
	RowId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.[WorkRole] SET (LOCK_ESCALATION = TABLE)
GO
--====================================
ALTER TABLE dbo.[RatingTask] ADD CONSTRAINT
	[IX_RatingTask_RowId] UNIQUE NONCLUSTERED 
	(
	RowId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.[RatingTask] SET (LOCK_ESCALATION = TABLE)
GO
--====================================
ALTER TABLE dbo.[CourseContext] ADD CONSTRAINT
	[IX_CourseContext_RowId] UNIQUE NONCLUSTERED 
	(
	RowId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.[CourseContext] SET (LOCK_ESCALATION = TABLE)
GO
--====================================
ALTER TABLE dbo.[Organization] ADD CONSTRAINT
	[IX_Organization_RowId] UNIQUE NONCLUSTERED 
	(
	RowId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.[Organization] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
go