//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserRoleFunctionSummary
    {
        public string Email { get; set; }
        public string UserName { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public string UserRole { get; set; }
        public string ApplicationFunction { get; set; }
        public string CodedNotation { get; set; }
    }
}
