//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptSchemeSummary
    {
        public int ConceptSchemeId { get; set; }
        public string Name { get; set; }
        public int conceptid { get; set; }
        public int ListId { get; set; }
        public string Concept { get; set; }
        public string CodedNotation { get; set; }
        public string Description { get; set; }
        public string AlternateLabel { get; set; }
        public System.Guid ConceptUID { get; set; }
        public bool IsActive { get; set; }
        public string WorkElementType { get; set; }
    }
}
