//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingTaskSummary
    {
        public int Id { get; set; }
        public int RankId { get; set; }
        public string Rank { get; set; }
        public int LevelId { get; set; }
        public string Level { get; set; }
        public int FunctionalAreaId { get; set; }
        public string FunctionalArea { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string Source { get; set; }
        public string SourceDate { get; set; }
        public Nullable<int> WorkElementTypeId { get; set; }
        public string WorkElementType { get; set; }
        public Nullable<int> TaskApplicabilityId { get; set; }
        public string TaskApplicability { get; set; }
        public Nullable<int> FormalTrainingGapId { get; set; }
        public string FormalTrainingGap { get; set; }
        public string CIN { get; set; }
        public string CourseName { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> TrainingTaskId { get; set; }
        public string TaskStatement { get; set; }
        public string CurrentAssessmentApproach { get; set; }
        public string CurriculumControlAuthority { get; set; }
        public string LifeCycleControlDocument { get; set; }
        public string Notes { get; set; }
        public string CodedNotation { get; set; }
        public Nullable<System.Guid> PayGradeType { get; set; }
        public Nullable<System.Guid> HasReferenceResource { get; set; }
        public Nullable<System.Guid> ReferenceType { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ApplicabilityType { get; set; }
        public Nullable<System.Guid> TrainingGapType { get; set; }
        public Nullable<System.Guid> HasTrainingTask { get; set; }
    }
}
