//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmtlSummary
    {
        public string Rating { get; set; }
        public string Rank { get; set; }
        public string Level { get; set; }
        public string BilletTitle { get; set; }
        public string FunctionalArea { get; set; }
        public string SourceDate { get; set; }
        public string WorkElementType { get; set; }
        public string TaskApplicability { get; set; }
        public string FormalTrainingGap { get; set; }
        public string CIN { get; set; }
        public string CourseName { get; set; }
        public string CurriculumControlAuthority { get; set; }
        public string LifeCycleControlDocument { get; set; }
        public string RMTLProject { get; set; }
        public string RatingTask { get; set; }
        public string TrainingTask { get; set; }
        public string ReferenceResource { get; set; }
        public string CourseTypes { get; set; }
        public string AssessmentMethodTypes { get; set; }
    }
}
