//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTaskSummary
    {
        public int CourseId { get; set; }
        public System.Guid CourseUID { get; set; }
        public string CourseName { get; set; }
        public int TrainingTaskId { get; set; }
        public string TrainingTask { get; set; }
        public System.Guid TrainingTaskUID { get; set; }
        public Nullable<int> CurriculumControlAuthorityId { get; set; }
        public string CurriculumControlAuthority { get; set; }
        public string LifeCycleControlDocument { get; set; }
        public System.Guid LifeCycleControlDocumentUID { get; set; }
        public string CourseTypes { get; set; }
        public string CTID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public string CodedNotation { get; set; }
        public Nullable<System.Guid> CurriculumControlAuthorityUID { get; set; }
        public Nullable<int> LifeCycleControlDocumentTypeId { get; set; }
        public string CurrentAssessmentApproach { get; set; }
    }
}
