//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserRoles_Summary
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string SortName { get; set; }
        public string RoleName { get; set; }
        public string RoleId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string AspNetId { get; set; }
    }
}
