//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_ABF_RMTL
    {
        public string Rating { get; set; }
        public string Rank { get; set; }
        public string RankLevel { get; set; }
        public string Billet_Title { get; set; }
        public string Functional_Area { get; set; }
        public string Source { get; set; }
        public string Date_of_Source { get; set; }
        public string Work_Element_Type { get; set; }
        public string Work_Element_Task { get; set; }
        public string Task_Applicability { get; set; }
        public string Formal_Training_Gap { get; set; }
        public string CIN { get; set; }
        public string Course_Name { get; set; }
        public string Course_Type { get; set; }
        public string Curriculum_Control_Authority_CCA { get; set; }
        public string Life_Cycle_Control_Document { get; set; }
        public string Task_Statement { get; set; }
        public string Current_Assessment_Approach { get; set; }
        public string NEC_Refresher_Training_Selection { get; set; }
        public string Journeyman { get; set; }
        public string Master { get; set; }
        public string Notes { get; set; }
    }
}
