//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_RMTLStaging
    {
        public string Unique_Identifier { get; set; }
        public string Rating { get; set; }
        public string Rank { get; set; }
        public string Level_A_J_M { get; set; }
        public string Billet_Title { get; set; }
        public string Functional_Area { get; set; }
        public string Source { get; set; }
        public string Date_of_Source { get; set; }
        public string Work_Element_Type { get; set; }
        public string Work_Element_Task { get; set; }
        public string Task_Applicability { get; set; }
        public string Formal_Training_Gap { get; set; }
        public string CIN { get; set; }
        public string Course_Name { get; set; }
        public string Course_Type_A_C_G_F_T { get; set; }
        public string Curriculum_Control_Authority_CCA { get; set; }
        public string Life_Cycle_Control_Document { get; set; }
        public string CTTL_PPP_TCCD_Statement { get; set; }
        public string Current_Assessment_Approach { get; set; }
        public string Part2Notes { get; set; }
        public string Training_Solution_Type { get; set; }
        public string Cluster_Analysis_Title { get; set; }
        public string Recommended_Modality { get; set; }
        public string Development_Specification { get; set; }
        public string Candidate_Platform { get; set; }
        public string CFM_Placement { get; set; }
        public string Priority_Placement { get; set; }
        public string Development_Ratio { get; set; }
        public string Development_Time { get; set; }
        public string EstimatedInstructionalTime { get; set; }
        public string Part3Notes { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
