//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.RmtlProject_Billet = new HashSet<RmtlProject_Billet>();
            this.Job_HasRating = new HashSet<Job_HasRating>();
        }
    
        public int Id { get; set; }
        public string CTID { get; set; }
        public string Name { get; set; }
        public string CodedNotation { get; set; }
        public Nullable<int> JobVersion { get; set; }
        public string Description { get; set; }
        public string ShortName30 { get; set; }
        public string ShortName14 { get; set; }
        public string CredentialRegistryId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> LastPublished { get; set; }
        public System.Guid RowId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmtlProject_Billet> RmtlProject_Billet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_HasRating> Job_HasRating { get; set; }
    }
}
