//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavyRegistryHistorySummaryByHour
    {
        public string ActivityDate { get; set; }
        public string ActivityType { get; set; }
        public Nullable<int> PeriodCount { get; set; }
    }
}
