//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtectedSystemEntities
    {
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public System.Guid EntityRowId { get; set; }
    }
}
