//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class QMRMTL_UniqueBilletLevelFuncationalAreaSourceWorkElementType
    {
        public string BilletTitle { get; set; }
        public string Level { get; set; }
        public string FunctionalArea { get; set; }
        public string Source { get; set; }
        public string WorkElementType { get; set; }
    }
}
