//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingContext_WorkRole
    {
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public int RatingContextId { get; set; }
        public int WorkRoleId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual RatingContext RatingContext { get; set; }
        public virtual WorkRole WorkRole { get; set; }
    }
}
