//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingContextV2
    {
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public int RatingId { get; set; }
        public System.Guid RatingTaskId { get; set; }
        public Nullable<System.Guid> BilletTitleId { get; set; }
        public System.Guid PayGradeTypeId { get; set; }
        public Nullable<System.Guid> TaskApplicabilityId { get; set; }
        public Nullable<System.Guid> FormalTrainingGapId { get; set; }
        public Nullable<System.Guid> TrainingTaskId { get; set; }
        public Nullable<System.Guid> ClusterAnalysisId { get; set; }
        public Nullable<int> TaskStatusId { get; set; }
        public string CodedNotation { get; set; }
        public string Notes { get; set; }
        public string CTID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
    }
}
