//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingTaskBillets
    {
        public int Id { get; set; }
        public int RatingTaskId { get; set; }
        public int JobId { get; set; }
        public string BilletTitles { get; set; }
    }
}
