//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rating()
        {
            this.Job = new HashSet<Job>();
            this.RatingTask_HasRating = new HashSet<RatingTask_HasRating>();
            this.RatingTask_HasRatingContext = new HashSet<RatingTask_HasRatingContext>();
            this.RatingContext = new HashSet<RatingContext>();
        }
    
        public int Id { get; set; }
        public string CTID { get; set; }
        public string Name { get; set; }
        public string CodedNotation { get; set; }
        public string Description { get; set; }
        public string MainEntityOfPage { get; set; }
        public string Version { get; set; }
        public string RatingUploadDate { get; set; }
        public string RatingPublicationDate { get; set; }
        public string Image { get; set; }
        public System.Guid RowId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingTask_HasRating> RatingTask_HasRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingTask_HasRatingContext> RatingTask_HasRatingContext { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingContext> RatingContext { get; set; }
    }
}
