//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceResourceCategoryConcepts
    {
        public int ConceptSchemeId { get; set; }
        public string ConceptScheme { get; set; }
        public int conceptid { get; set; }
        public string Concept { get; set; }
        public string CodedNotation { get; set; }
        public string Description { get; set; }
        public string WorkElementType { get; set; }
        public int IsAWorkElementType { get; set; }
        public Nullable<int> ListId { get; set; }
        public string CTID { get; set; }
    }
}
