//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryHistory
    {
        public int Id { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string ActivityType { get; set; }
        public string ActivityLabel { get; set; }
        public string Event { get; set; }
        public string Comment { get; set; }
        public string ActivityObjectIdentifier { get; set; }
        public string RegistryUrl { get; set; }
        public string RelatedUrl { get; set; }
        public string DataOwnerCTID { get; set; }
        public Nullable<int> ActivityObjectId { get; set; }
        public Nullable<int> ObjectRelatedId { get; set; }
        public Nullable<int> TargetObjectId { get; set; }
        public Nullable<System.DateTime> ActivityDateCentral { get; set; }
    }
}
