//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMTLImport_211109
    {
        public string Rating { get; set; }
        public Nullable<int> RankId { get; set; }
        public string Rank { get; set; }
        public Nullable<int> LevelId { get; set; }
        public string Level { get; set; }
        public Nullable<int> BilletTitleId { get; set; }
        public string BilletTitle { get; set; }
        public Nullable<int> FunctionalAreaId { get; set; }
        public string FunctionalArea { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string Source { get; set; }
        public string SourceDate { get; set; }
        public Nullable<int> WorkElementTypeId { get; set; }
        public string WorkElementType { get; set; }
        public Nullable<int> RatingLevelTaskId { get; set; }
        public string WorkElementTask { get; set; }
        public string Task_Applicability { get; set; }
        public Nullable<int> FormalTrainingGapId { get; set; }
        public string Formal_Training_Gap { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CIN { get; set; }
        public string Course_Name { get; set; }
        public string Course_Type { get; set; }
        public string Curriculum_Control_Authority { get; set; }
        public string Life_Cycle_Control_Document { get; set; }
        public Nullable<int> CourseTaskId { get; set; }
        public string Task_Statement { get; set; }
        public Nullable<int> AssessmentId { get; set; }
        public string Current_Assessment_Approach { get; set; }
        public string NEC_Refresher_Training_Selection { get; set; }
        public string Journeyman_Core_Training_Selection { get; set; }
        public string Master_Core_Training_Selection { get; set; }
        public string Notes { get; set; }
    }
}
