//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmtlProject_Billet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RmtlProject_Billet()
        {
            this.RmtlProjectBilletTask = new HashSet<RmtlProjectBilletTask>();
        }
    
        public int Id { get; set; }
        public int RmtlProjectId { get; set; }
        public int JobId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual RMTLProject RMTLProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmtlProjectBilletTask> RmtlProjectBilletTask { get; set; }
    }
}
