//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmtlProjectBilletTask
    {
        public int Id { get; set; }
        public int ProjectBilletId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int RatingTaskId { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public System.Guid RowId { get; set; }
    
        public virtual RmtlProject_Billet RmtlProject_Billet { get; set; }
        public virtual RatingTask RatingTask { get; set; }
    }
}
