//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription_EntityType
    {
        public int Id { get; set; }
        public int SubscriptionId { get; set; }
        public int EntityTypeId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Codes_EntityType Codes_EntityType { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
