//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkRole
    {
        public int Id { get; set; }
        public string CTID { get; set; }
        public string Name { get; set; }
        public string CodedNotation { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public string CredentialRegistryId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> LastPublished { get; set; }
        public System.Guid RowId { get; set; }
    }
}
