using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Data.Tables
{
	//Interface to constrain specific properties to make updates easier across multiple tables
	public interface DBEntityBaseObject
	{
		int Id { get; set; }
		Guid RowId { get; set; }
		DateTime Created { get; set; }
		int? CreatedById { get; set; }
		DateTime LastUpdated { get; set; }
		int? LastUpdatedById { get; set; }
		string CTID { get; set; }
	}

	//Tables whose classes are auto-generated by Entity Framework, but which also need to implement the above interface
	public partial class Rating : DBEntityBaseObject { }
	public partial class Organization : DBEntityBaseObject { }
	public partial class ReferenceResource : DBEntityBaseObject { }
	public partial class Job : DBEntityBaseObject { }
	public partial class WorkRole : DBEntityBaseObject { }
	public partial class ClusterAnalysisTitle : DBEntityBaseObject { }
	public partial class Course : DBEntityBaseObject { }
	public partial class TrainingTask : DBEntityBaseObject { }
	public partial class RatingTask : DBEntityBaseObject { }
	public partial class ClusterAnalysis : DBEntityBaseObject { }
	public partial class CourseContext : DBEntityBaseObject { }
	public partial class RatingContext : DBEntityBaseObject { }
	public partial class ConceptScheme : DBEntityBaseObject { }
	public partial class ConceptScheme_Concept : DBEntityBaseObject { }
	public partial class RMTLProject : DBEntityBaseObject { }


	//Multi-value item table interface
	public interface DBEntityJoinTableItem
	{
		int Id { get; set; }
		Guid RowId { get; set; }
		DateTime Created { get; set; }
		int? CreatedById { get; set; }
	}

	//Multi-value item tables that implement the above interface
	public partial class ClusterAnalysis_HasCandidatePlatform : DBEntityJoinTableItem { }
	public partial class ClusterAnalysis_CFMPlacementType : DBEntityJoinTableItem { }
	public partial class CourseContext_AssessmentType : DBEntityJoinTableItem { }
	public partial class ReferenceResource_ReferenceType : DBEntityJoinTableItem { }
	public partial class Course_CourseType : DBEntityJoinTableItem { }

}
